"""Add Likes table

Revision ID: 53347315be17
Revises: 9ac86a8f071d
Create Date: 2026-05-12 22:19:17.319130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53347315be17'
down_revision = '9ac86a8f071d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('liker_id', sa.Integer(), nullable=False),
    sa.Column('liked_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('liker_id != liked_id', name='ck_no_self_like'),
    sa.ForeignKeyConstraint(['liked_id'], ['profile.id'], ),
    sa.ForeignKeyConstraint(['liker_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('liker_id', 'liked_id', name='uq_like_pair')
    )
    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.create_index('ix_likes_liked_id', ['liked_id'], unique=False)
        batch_op.create_index('ix_likes_liker_id', ['liker_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.drop_index('ix_likes_liker_id')
        batch_op.drop_index('ix_likes_liked_id')

    op.drop_table('likes')
    # ### end Alembic commands ###
