"""Update profile and interest schema

Revision ID: d2feaf5e4c87
Revises: 947038e46efd
Create Date: 2026-05-09 15:32:51.845750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2feaf5e4c87'
down_revision = '947038e46efd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interest', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interest_category'))
        batch_op.drop_column('category')

    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('orientation', sa.String(length=30), nullable=False))
        batch_op.alter_column('age',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('gender',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
        batch_op.alter_column('location_text',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('latitude',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('longitude',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('place_id',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.alter_column('place_id',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
        batch_op.alter_column('longitude',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('latitude',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('location_text',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('gender',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
        batch_op.alter_column('age',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('orientation')

    with op.batch_alter_table('interest', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.VARCHAR(length=50), nullable=True))
        batch_op.create_index(batch_op.f('ix_interest_category'), ['category'], unique=False)

    # ### end Alembic commands ###
